name: website
description: jhihyu's personal website
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase_ui_auth: ^1.1.9
  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_ui_oauth_google: ^1.0.16
  firebase_ui_oauth_facebook: ^1.0.16
  firebase_ui_oauth_twitter: ^1.0.16
  animated_text_kit: ^4.2.2
  url_launcher: ^6.1.8
  http: ^0.13.5
  firebase_app_check: ^0.1.1+8
  flutter_colorpicker: ^1.0.3
  provider: ^6.0.5
  qr_flutter: ^4.0.0
  image_picker: ^0.8.6+1
  three_dart: ^0.0.16
  three_dart_jsm: ^0.0.10
  flutter_gl: ^0.0.21
  google_fonts: ^4.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dependency_validator: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
  - family: Logo
    fonts:
      - asset: assets/fonts/Logo.ttf