name: Build and Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - deploy
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Archive
          path: out

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEBPAGE_349C7 }}'
          channelId: live
          projectId: webpage-349c7
          entryPoint: .

      - name: Cloudflare Purge Cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
          # Zone is required by both authentication methods
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}

          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          # ...or:
          # CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          # CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}
